modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="testi"
version="1.0.0"
displayName="testi"
credits="nomn"
displayURL="https://chao-island.com/viewer/"
logoFile="logo.png"
authors="superkid250"
description='''
UNKONOW YET
'''

[[dependencies.testi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




